### PR TITLE
Update the firmware to extract MP61_0116_B17, which is more compatibl…

### PR DESCRIPTION
**Pull request by wy414012**
Update the firmware to extract MP61_0116_B17, which is more compatible with Xeon v1 v2 processors. (Tested and passed)

### CODE REVIEW

**Comment by vit9696** [comment]
Use legacy for these processors.

**Comment by wy414012** [comment]
Hello, what should I do if the GUI interface cannot be enabled using legacy? Adding OpenCanopy.efi to the test will result in a black screen and stuck. I cannot determine if it is an HFS error or an OpenCanopy error. The problem disappeared after replacing the extracted HfsPlus.

**Comment by vit9696** [comment]
Use HfsPlus**Legacy**.efi.

**Comment by wy414012** [comment]
This driver is currently being used, and it will cause a black screen after GUI boot is added.
[EFI](https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2/tree/master/OpenCore/V1%E7%89%88%E6%9C%ACU%E7%94%A8/EFI/OC/Drivers)

**Pull request closed without merging**
